use std::collections::BTreeSet;

use egui_code_editor::Syntax;

pub fn waql_syntax() -> Syntax {
    Syntax {
        language: "rust",
        // case_sensitive: false,
        keywords: BTreeSet::from([
            "object",
            "type",
            "query",
            "search",
            "project",
            // Expressions
            "children",
            "descendants",
            "this",
            "parent",
            "ancestors",
            "referencesTo",
        ]),
        types: BTreeSet::from([
            "AcousticTexture",
            "Action",
            "ActionException",
            "ArgumentsSlot",
            "Attenuation",
            "AudioDevice",
            "AudioFileSource",
            "AuxBus",
            "BlendContainer",
            "BlendTrack",
            "Bus",
            "ControlSurfaceBinding",
            "ControlSurfaceBindingGroup",
            "ControlSurfaceSession",
            "Conversion",
            "Curve",
            "CustomState",
            "DialogueEvent",
            "Effect",
            "EffectSlot",
            "EntryPathSlot",
            "Event",
            "ExternalSource",
            "ExternalSourceFile",
            "Folder",
            "GameParameter",
            "Language",
            "Marker",
            "MediaPoolDatabase",
            "MediaPoolDatabasePath",
            "MediaPoolFilter",
            "MediaPoolQuery",
            "Metadata",
            "MetadataSlot",
            "MidiFileSource",
            "MidiParameter",
            "MixingSession",
            "Modifier",
            "ModulatorEnvelope",
            "ModulatorLfo",
            "ModulatorTime",
            "MultiSwitchEntry",
            "MusicArgumentsSlot",
            "MusicClip",
            "MusicClipMidi",
            "MusicCue",
            "MusicEventCue",
            "MusicFade",
            "MusicPlaylistContainer",
            "MusicPlaylistItem",
            "MusicSegment",
            "MusicStinger",
            "MusicSwitchContainer",
            "MusicTrack",
            "MusicTrackSequence",
            "MusicTransition",
            "ObjectSettingAssoc",
            "Panner",
            "Path2D",
            "Platform",
            "PlaylistSlot",
            "PluginDataSource",
            "Position",
            "Project",
            "PropertyContainer",
            "Query",
            "RandomSequenceContainer",
            "RTPC",
            "SearchCriteria",
            "SidechainMix",
            "Sound",
            "SoundBank",
            "SoundcasterSession",
            "SourcePlugin",
            "State",
            "StateGroup",
            "StateGroupInfo",
            "Switch",
            "SwitchContainer",
            "SwitchGroup",
            "Trigger",
            "UserProjectSettings",
            "WorkUnit",
        ]),
        special: BTreeSet::from([
            "$", "@", "from", "where", "skip", "take", "select", "orderby", "distinct",
        ]),
        ..Syntax::default()
    }
}
