//! WAQL 语法定义
//!
//! 定义 WAQL (Wwise Authoring Query Language) 的语法规则，
//! 包括关键字、类型和特殊符号

use std::collections::BTreeSet;

use egui_code_editor::Syntax;

/// 创建 WAQL 语法定义
///
/// # Returns
///
/// 返回配置好的 WAQL 语法对象，用于代码编辑器的语法高亮
pub fn waql_syntax() -> Syntax {
    Syntax {
        language: "waql",
        keywords: BTreeSet::from([
            "object",
            "type",
            "query",
            "search",
            "project",
            "children",
            "descendants",
            "this",
            "parent",
            "ancestors",
            "referencesTo",
            "owner",
            "randomizer",
            "state",
            "workunit",
            "musicTransitionRoot",
            "musicTransitionObject",
            "musicPlaylistRoot",
            "maxDurationSource",
            "maxDurationSourceObject",
            "maxRadiusAttenuation",
            "maxRadiusAttenuationObject",
            "audioSourceLanguage",
            "switchContainerChildContext",
            "switchGroupGameParameter",
            "panner",
            "stateGroups",
            "customStates",
            "originalState",
            "extractEvents",
            "extractStructures",
            "extractMedia",
            "soundbanksReferencingEvent",
        ]),
        types: BTreeSet::from([
            "AcousticTexture",
            "Action",
            "ActionException",
            "ActorMixer",
            "Attenuation",
            "AudioDevice",
            "AudioFileSource",
            "AuxBus",
            "BlendContainer",
            "BlendTrack",
            "Bus",
            "ControlSurfaceBinding",
            "ControlSurfaceBindingGroup",
            "ControlSurfaceSession",
            "Conversion",
            "Curve",
            "CustomState",
            "DialogueEvent",
            "Effect",
            "EffectSlot",
            "Event",
            "ExternalSource",
            "ExternalSourceFile",
            "Folder",
            "GameParameter",
            "Language",
            "Marker",
            "Metadata",
            "MidiFileSource",
            "MidiParameter",
            "MixingSession",
            "Modifier",
            "ModulatorEnvelope",
            "ModulatorLfo",
            "ModulatorTime",
            "MultiSwitchEntry",
            "MusicClip",
            "MusicClipMidi",
            "MusicCue",
            "MusicEventCue",
            "MusicFade",
            "MusicPlaylistContainer",
            "MusicPlaylistItem",
            "MusicSegment",
            "MusicStinger",
            "MusicSwitchContainer",
            "MusicTrack",
            "MusicTrackSequence",
            "MusicTransition",
            "ObjectSettingAssoc",
            "Panner",
            "Path2D",
            "Platform",
            "PluginDataSource",
            "Position",
            "Project",
            "Query",
            "RTPC",
            "RandomSequenceContainer",
            "SearchCriteria",
            "Sound",
            "SoundBank",
            "SoundcasterSession",
            "SourcePlugin",
            "State",
            "StateGroup",
            "Switch",
            "SwitchContainer",
            "SwitchGroup",
            "Trigger",
            "UserProjectSettings",
            "WorkUnit",
        ]),
        special: BTreeSet::from([
            "$", "@", "from", "where", "skip", "take", "select", "orderby", "distinct", "any",
            "all", "first", "last", "at", "and", "or"
        ]),
        ..Syntax::default()
    }
}
